### ISSUE TITLE
No external Moodle connected, this option appears and I already followed the steps . in moodle 3.9

### ISSUE THREAD

**Issue by danielddltellez** [cperves/moodle-block-my_external_backup_restore_courses#11]
No external Moodle connected, this option appears and I already followed the steps . in moodle 3.9

**Comment by danielddltellez** [comment]
![Captura](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/44476349/9705dd71-ba00-4c85-a58f-21463bd9955a)

**Comment by danielddltellez** [comment]
I don't see any course to restore, and I already made the manual settings. You can support me

**Comment by cperves** [comment]
Hello, do you have the correct version of the plugin the last one is for Moodle 4.1

**Comment by danielddltellez** [comment]
My version moodle is 3.9 , the version plugin is 2.1.2. update to version 3.1.1

**Comment by danielddltellez** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/44476349/71382087-0c52-4a7c-bdce-c87828cedc33)

**Comment by cperves** [comment]
yes unfortunately the last version is for 4.1 Moodle version

**Comment by cperves** [comment]
In the README.md file of last version you'll find under Troubleshooting section somme webservice url usefull to test communication beetween the client Moodle and the Moodle server, this is usefull to detect troubles

**Comment by cperves** [comment]
I copy the interesting content here


## Troubleshooting
In case of troubles with message "error/site name can't be retrieved for ..."
* check that the token is correct and that external_moodles is correctly filled in plugin settings
* check that your https configuration is correct in web server including valid ssl certificate
* you can test the webservice with url :
  * `https://mywebsite/webservice/rest/server.php?wstoken=xxxxxxxxxxxxxxx&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses&username=USERNAME&concernedroles=AROLE
    * will return the list of remote courses
    * for user with username USERNAME
    * who has AROLE role in courses
* `https://mywebsite/webservice/rest/server.php?wstoken=XXXXXXXXXXXXXXX&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses_zip&username=USERNAME&courseid=COURSEID`
    * will return {"filename":"", "filerecord":XXXXXXX}
    * for user USERNAME
    * in course COURSEID
## if curl requests seems to be blocked
* Go to HttpSettings of the moodles
  * Go to Administration -> Security -> HTTP security
  * check settings
  * and above all check curlsecurityblockedhosts content, you maybe have to had remote moodle ip

**Comment by danielddltellez** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/44476349/95de3845-4734-4455-bf62-ba676e0f99c0)

My test &moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses&username=block_my_external_backup_restore_courses_user&concernedroles=manager 


It does not return information to me, I have doubts about the role we have to place and the user.
The user is the one we created with the cli, what role do you recommend placing in the webservice

**Comment by ted-strauss-K1** [comment]
Please make sure your user is **enrolled** in the course.

**Comment by cperves** [comment]
the username is not the webservice affected one but the of your users that is enrolled in a remote course with the role set in the plugin settings

**Comment by cperves** [comment]
@danielddltellez  did you solve the problem?
