### ISSUE TITLE
Restore course for user - The URL is blocked 

### ISSUE THREAD

**Issue by ted-strauss-K1** [cperves/moodle-block-my_external_backup_restore_courses#13]
I'm attempting to use the plugin to restore a course from remote server.
The client moodle I'm using for testing is localhost. 

I can get data with function `block_my_external_backup_restore_courses_get_courses`.
https://sandbox-moodle41.example.com/webservice/rest/server.php?wstoken=a84bc82cdad69e0f8cc8f387e025xxxx&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses&username=user.name&concernedroles=editingteacher

Returns this.
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/930560/5c4b5521-187b-41c2-8702-117e60e9d116)

So the connection is good.

But when I use plugin interface to do Restore course for user, I get error "The URL is blocked"

![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/930560/a6745265-ce32-411d-98b8-d472a8a94d6d)

How can I add localhost client moodle to CURL whitelist on HTTP Security ??
How can I debug this issue?
Thank you

**Comment by ted-strauss-K1** [comment]
Running this - is it missing any argument?
https://sandbox-moodle41.example.com/webservice/rest/server.php?wstoken=a84bc82cdad69e0f8cc8f387xxxxxxxx&wsfunction=core_course_get_courses_by_field&moodlewsrestformat=json

Returns that - because REST call returns "The URL is blocked":
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/930560/a55c4d00-3bc5-48d3-8afe-6fcf8e210953)

**Comment by cperves** [comment]
> But when I use plugin interface to do Restore course for user, I get error "The URL is blocked"
> 
> ![image](https://private-user-images.githubusercontent.com/930560/301549671-a6745265-ce32-411d-98b8-d472a8a94d6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDE2MTcsIm5iZiI6MTcwNzE0MTMxNywicGF0aCI6Ii85MzA1NjAvMzAxNTQ5NjcxLWE2NzQ1MjY1LWNlMzItNDExZC05OGI4LWQ0NzJhOGE5NGQ2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMzU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGRlOTBkZDcwYTY1NTVhZDA5MzBjYTU2ZjljYjBjNTMyYjliZTQzMGU4ZjMwOTkzOGJkMjIzNWNmNzg3ZmI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XLHaTAmiRo2s5M5YZ6WWLV8pkqH2mchJz3m27fSvGsg)
> 
> How can I add localhost client moodle to CURL whitelist on HTTP Security ?? How can I debug this issue? Thank you

2 possibilities :
- Moodle block the curl request, see security parameters on Moodle admin ( Administration ->   Security ->  HTTP security)
- Curl does not accept your certificate
  - you need to force the download of your certificate
  - here my old procédure while working with self signed certificate on my dev machine, maybe too old
  - search openssldir to place your certificate :   - ` openssl version -d`
  - edit the certificate config 
```ssh
locate ca-certificates.conf
vim /etc/ca-certificates.conf
```
  - add your certificate name
  - save and update with `update-ca-certificates --fresh`
Hope this will resolve your trouble

**Comment by cperves** [comment]
> Running this - is it missing any argument? https://sandbox-moodle41.example.com/webservice/rest/server.php?wstoken=a84bc82cdad69e0f8cc8f387xxxxxxxx&wsfunction=core_course_get_courses_by_field&moodlewsrestformat=json
> 
> Returns that - because REST call returns "The URL is blocked": ![image](https://private-user-images.githubusercontent.com/930560/301558967-a55c4d00-3bc5-48d3-8afe-6fcf8e210953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDE2MTcsIm5iZiI6MTcwNzE0MTMxNywicGF0aCI6Ii85MzA1NjAvMzAxNTU4OTY3LWE1NWM0ZDAwLTNiYzUtNDhkMy04YWZlLTZmY2Y4ZTIxMDk1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxMzU1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDY3MzU2MTQ4ZTE3OTRmM2VlMzVhOTZmNjFjNzA0NzU0NzY3NjRlZmU1YWY1ZTAxYWE1NmZkNjYzZjMyYmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RqnIwZaBBhWuOpTKYXbQkpJ53FNIKKMsuxsgWBfzg5E)

I just try this one with my local moodle instance and my token and I had not troubles

**Comment by cperves** [comment]
just to be sure, what is your moodle version?

**Comment by cperves** [comment]
from what I see in moodle code with courseformatoption the only call in our case is `$courseformatoptions = course_get_format($course)->get_config_for_external();`
may be an error in one of the courseformat settings or options

**Comment by ted-strauss-K1** [comment]
Thanks for the tips. I'm continuing to work on it, and will report once I have a solution.
