### ISSUE TITLE
Unable to install in 3.8 Moodle instances

### ISSUE THREAD

**Issue by psugumar87** [cperves/moodle-block-my_external_backup_restore_courses#7]
Hi,

We tried to install the plugin in our 3.8 instance but receive the error as shown in the screenshot. 

Can this be fixed? 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77225432/104117958-5ceb3a00-5379-11eb-9c99-eb2e5d91493c.png)

**Comment by cperves** [comment]
this bug occured with tagged version
it was corrected in march in main branch
I test a fresh install on a 3.9 version moodle and main branch version of the plugin
Sorry I didn't tag the version because I didn't have time to make some tests on 3.8 and 3.9 versions

**Comment by cperves** [comment]
I tagged it now as release candidate 1.3-RC1-moodle-3.9
Working on it
If it is ok and work for your 3.8 version , I'll tag it again and publish on moodle.org site

**Comment by cperves** [comment]
In case of erreors I'll correct them as soon as possible

**Comment by cperves** [comment]
solved afte rinstalling last version
