### ISSUE TITLE
Trouble setting client moodle

### ISSUE THREAD

**Issue by nandiwardhanawidianto** [cperves/moodle-block-my_external_backup_restore_courses#8]
can you give me example what this means ? 
**in my_external_backup_course | externalmoodles formatted list of course servers moodles formatted as moodle_url1,token_compte_webservice_moodle_externe1;moodle_url2,token_compte_webservice_moodle_externe2;...**

I install the plugin both client n server. but i dont understand what i'm supposed to fill in external moodles. Can you be more spesific ?

Thanks appreciate your help 
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/e8a77866-64ff-4c5e-9fa2-f7c0357f23c5)

**Comment by cperves** [comment]
Hello, in this section you have to put the url of the remote moodle with the token created separated by a comma
for example 
```
https://localhost/cds,XXXXXXXXXXXXXXXX;
```

The creation of  the webservice token for  the plugin is described in README.md  in the section Installation ->  webservice settings

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/37708a2c-fe38-4ca6-b730-f47ca621a176)

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/dc49071e-8e75-4e80-8fe3-1822649fdd35)


![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/98c664e2-5c9c-4749-ab85-966ecc77b8cf)

I'm sorry it still trouble me, i already done that, or i still making mistake that i dont know. PLEASE HELP

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/f9cdf4ba-3f46-45f3-8e06-786bcd68e593)

**Comment by cperves** [comment]
- is your https certificate valide?
- have you so trace in apache/nginx error log?

**Comment by cperves** [comment]
which version of moodle have you and which version of the plugin have you?

**Comment by nandiwardhanawidianto** [comment]
no my moodle is not https valide, 

My Moodle client n server version is both 401 Stable or 4.1.3 

The plugin version is 3.0.2 (2023051000)

**Comment by cperves** [comment]
the trouble may comme from the not valide https, curl doesn't accept not valide certificates
try with http protocole

**Comment by nandiwardhanawidianto** [comment]
Sorry still the same error

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/1e81b62a-8bff-4203-bf83-df55794d8a7c)

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/ea82ee29-7a2b-4147-9cf5-fb3cf00ed93f)

**Comment by nandiwardhanawidianto** [comment]
FYI, i install on localhost computer using xamp. drop your plugin in both moodle client n remote moodle(CDS). install both plugin in moodle. 

setting the user role n capabilities, generate token in remote Moodle (CDS) and type the token along with the url remote moodle (CDS). but still the same erorr

**Comment by nandiwardhanawidianto** [comment]
Or maybe the problems come from i install moddle on xampp ? What do you think ? 

I pretty hopeless, and i need this plugin running on my moodle.

**Comment by cperves** [comment]
You are going to test the webservice with their url
https://mywebsite/webservice/rest/server.php?wstoken=xxxxxxxxxxxxxxx&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses&username=admin&concernedroles=editingteacher

last thing have you put a return after the url,token. line
if yes remove it

**Comment by cperves** [comment]
the first webservice will return list of remote courses where user with username has the role editingteacher in course (the role is set in plugin setting)

**Comment by cperves** [comment]
this is the second one wich generate the remotely backup course file
https://mywebsite/webservice/rest/server.php?wstoken=XXXXXXXXXXXXXXX&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses_zip&username=USERNAME&courseid=COURSEID

it will will return {"filename":"", "filerecord":XXXXXXX}

**Comment by cperves** [comment]
> the first webservice will return list of remote courses where user with username has the role editingteacher in course (the role is set in plugin setting)

username must change with a username that have courses with role , you can change role as you wan't (the roles are the one selected in plugin setting)

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/56cfb0e7-7e03-4d36-b241-9504b3ffc472)

![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/1743344b-4d83-455f-87d3-9db18aa59559)


i test on POSTMAN and it give me

**Comment by cperves** [comment]
so web services works well and token user and role seems to be ok

**Comment by cperves** [comment]
are you 2 moodles enabled to communicate using curl
to test that you can curl the webservices in a commadline from the Moodle client machine

**Comment by nandiwardhanawidianto** [comment]
ok How to do that ? i already open curl on cli from moodle client machine directory. im not sure what im to do next (sorry im stil junior n learning}

![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/ddf03660-5765-4a28-89c6-d6733d56e3a9)

**Comment by cperves** [comment]
youve got to type  with the url of webservice 
curl 'mly_url_service'

**Comment by cperves** [comment]
e.g
curl 'https://mywebsite/webservice/rest/server.php?wstoken=xxxxxxxxxxxxxxx&moodlewsrestformat=json&wsfunction=block_my_external_backup_restore_courses_get_courses&username=USERNAME&concernedroles=AROLE'

**Comment by cperves** [comment]
maybe " instead of ' (i'm on linux not windows so not sure about text quotes)

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/6270a6a9-56b5-4d87-a0f9-16f6af10f922)
 
it did give me result tho

**Comment by cperves** [comment]
your 2 moodles are in the same server is'n it?
you can't use https in the plugin if your ssl certificate is not good

**Comment by nandiwardhanawidianto** [comment]
yes in the same server.  and i dont use https

**Comment by cperves** [comment]
so in the plugin moodle put http instead of https

**Comment by cperves** [comment]
I sent you an email

**Comment by nandiwardhanawidianto** [comment]
![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/4985b6cf-a32f-499a-b0e2-ec7466411605)

![image](https://github.com/cperves/moodle-block-my_external_backup_restore_courses/assets/62790811/90c2bf5a-6653-45da-93b5-e2e0d4220023)


Done but i stil get no connection

**Comment by nandiwardhanawidianto** [comment]
nandib02@gmail.com This is my email

**Comment by nandiwardhanawidianto** [comment]
> I sent you an email

I dont see your email in mu inbox, can i email you instead ?

**Comment by cperves** [comment]
Ok

**Comment by cperves** [comment]
Curl tested on command line -> no troubles
Webservices tested -> no troubles
Trouble wih moodle Http Security curlsecurityblockedhosts parameter

Well done @nandiwardhanawidianto 

I complete the README troubleshooting section with your case
